library("R6")

DbContext <- R6Class("DbContext", public = list(
  jornadas = 'Jornada',
  observador = "[Observador 1]",
  flota = "FLOTA",
  zonas = 'zonas2',
  lances = 'Lances',
  artes_lances = 'Artes',
  artes = 'codigos_xunta',
  especies_muestreadas = 'EspeciesM',
  especies = 'unique_especies_seleccionadas',
  muestreos = 'Muestreos',
  talla_columns = c(
    "ob.[Observador 1]",
    "j.idjornada",
    "Format(j.dia, 'd/m/yyyy') as dia",
    "z2.ZONA",
    "l.Nulo",
    "l.Idlance",
    "l.FLARG",
    "l.HorafL",
    "l.FVIR",
    "l.HorafV",
    "l.mcarte1",
    "l.[LAT inicio]",
    "l.[LON inicio]",
    "l.[LAT final]",
    "l.[LON final]",
    "l.TIPOFONDO",
    "l.PROFMax",
    "l.PROFMin",
    "l.PROFMed",
    "cax.ARTE",
    "em.Idartes",
    "uem.idespecie",
    "uem.ESPECIE",
    "m.CoD",
    "m.NUMINDIVS",
    "m.PESO",
    "m.TALLA"
  )
))